"""Coverage for per-chunk subtitle cues surviving P6 concat with the right offset.

Purpose
-------

When a user manually hand-tunes a chunk's SRT cues (e.g. via the Web UI
``SubtitleTimingEditor`` → an edited per-chunk SRT persisted to MinIO,
or a pre-existing per-chunk SRT generated by P5), the P6 concat step
must:

  1. compute each chunk's global offset via ``compute_chunk_offsets``,
     respecting per-shot padding vs cross-shot gap;
  2. shift every local cue by that offset in ``merge_srt_files``.

The existing ``tests/tasks/test_p6_logic.py`` exercises each function in
isolation but not the *combination* — which is exactly where a bug in
either side would slip through silently. These tests drive an integrated
scenario: three chunks across two shots with known durations and
hand-written (i.e. "manually edited") local cue timings, and assert the
exact absolute timestamps that end up in the merged SRT.

Strictly a test file — no business code is modified.
"""

from __future__ import annotations

import pytest

from server.core.p6_logic import (
    ChunkTiming,
    compute_chunk_offsets,
    compute_gap_sequence,
    compute_total_duration,
    format_srt_timestamp,
    merge_srt_files,
    parse_srt,
)


# ---------------------------------------------------------------------------
# Helpers — build a per-chunk SRT the way P5 / the UI editor would.
# ---------------------------------------------------------------------------


def _srt_from_cues(cues: list[tuple[float, float, str]]) -> str:
    """Render ``[(start, end, text), ...]`` as a standards-compliant SRT string.

    ``start`` / ``end`` are local to the chunk — i.e. relative to the start
    of the chunk's WAV, **not** to the final episode timeline.
    """
    out: list[str] = []
    for i, (start, end, text) in enumerate(cues, start=1):
        out.append(str(i))
        out.append(
            f"{format_srt_timestamp(start)} --> {format_srt_timestamp(end)}"
        )
        out.append(text)
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Integrated tests — offsets + merge applied together.
# ---------------------------------------------------------------------------


class TestSubtitleCueOffsetInP6Concat:
    """3-chunk mini-episode, 2 shots, with hand-crafted local cue timings."""

    PADDING_S = 0.2
    SHOT_GAP_S = 0.5

    # Durations chosen so the cumulative math is easy to eyeball:
    #   chunk1 duration = 1.0, chunk2 = 1.5, chunk3 = 2.0
    #   chunk1/chunk2 same shot  → gap = PADDING_S (0.2)
    #   chunk2/chunk3 cross shot → gap = SHOT_GAP_S (0.5)
    TIMINGS = [
        ChunkTiming("c1", "shot01", 0, 1.0),
        ChunkTiming("c2", "shot01", 1, 1.5),
        ChunkTiming("c3", "shot02", 0, 2.0),
    ]

    # Expected offsets:
    #   c1: 0.0
    #   c2: 0.0 + 1.0 + 0.2 = 1.2
    #   c3: 1.2 + 1.5 + 0.5 = 3.2
    EXPECTED_OFFSETS = [0.0, 1.2, 3.2]

    def test_compute_chunk_offsets_matches_expected(self):
        offsets = compute_chunk_offsets(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        assert offsets == pytest.approx(self.EXPECTED_OFFSETS)

        # Sanity: mirror via compute_gap_sequence + compute_total_duration.
        gaps = compute_gap_sequence(self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S)
        assert gaps == pytest.approx([self.PADDING_S, self.SHOT_GAP_S])
        total = compute_total_duration(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        # 3.2 (c3 offset) + 2.0 (c3 duration) = 5.2
        assert total == pytest.approx(5.2)

    def test_hand_edited_cues_are_offset_correctly_per_chunk(self):
        # Simulate the user manually editing per-chunk local cue timings.
        # Each cue's (start, end) is in the chunk's local frame ∈ [0, duration].
        per_chunk_cues = {
            "c1": [(0.0, 0.5, "first half of chunk one"),
                   (0.5, 1.0, "second half of chunk one")],
            "c2": [(0.1, 1.4, "chunk two single cue")],
            "c3": [(0.0, 0.8, "chunk three cue one"),
                   (1.0, 2.0, "chunk three cue two")],
        }

        srt_strings = [_srt_from_cues(per_chunk_cues[t.chunk_id]) for t in self.TIMINGS]
        offsets = compute_chunk_offsets(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        merged = merge_srt_files(srt_strings, offsets)

        cues = parse_srt(merged)
        # 2 + 1 + 2 = 5 total cues
        assert len(cues) == 5

        # Chunk1 offset = 0.0 → cues unchanged.
        assert cues[0].start_s == pytest.approx(0.0)
        assert cues[0].end_s == pytest.approx(0.5)
        assert cues[0].text == "first half of chunk one"
        assert cues[1].start_s == pytest.approx(0.5)
        assert cues[1].end_s == pytest.approx(1.0)

        # Chunk2 offset = 1.2 → (0.1, 1.4) → (1.3, 2.6)
        assert cues[2].start_s == pytest.approx(1.3)
        assert cues[2].end_s == pytest.approx(2.6)
        assert cues[2].text == "chunk two single cue"

        # Chunk3 offset = 3.2 → (0.0, 0.8) → (3.2, 4.0); (1.0, 2.0) → (4.2, 5.2)
        assert cues[3].start_s == pytest.approx(3.2)
        assert cues[3].end_s == pytest.approx(4.0)
        assert cues[3].text == "chunk three cue one"
        assert cues[4].start_s == pytest.approx(4.2)
        assert cues[4].end_s == pytest.approx(5.2)
        assert cues[4].text == "chunk three cue two"

    def test_merged_srt_is_renumbered_from_one_and_sorted_by_offset(self):
        per_chunk_cues = {
            "c1": [(0.0, 1.0, "a")],
            "c2": [(0.0, 1.5, "b")],
            "c3": [(0.0, 2.0, "c")],
        }
        srt_strings = [_srt_from_cues(per_chunk_cues[t.chunk_id]) for t in self.TIMINGS]
        offsets = compute_chunk_offsets(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        merged = merge_srt_files(srt_strings, offsets)

        # Extract numeric cue headers.
        numbers = [
            ln.strip()
            for ln in merged.splitlines()
            if ln.strip().isdigit()
        ]
        assert numbers == ["1", "2", "3"]

        # Cues must appear in concatenation order; time is strictly increasing.
        cues = parse_srt(merged)
        for prev, curr in zip(cues, cues[1:]):
            assert curr.start_s >= prev.end_s - 1e-9, (
                f"cues out of order: {prev.end_s} then {curr.start_s}"
            )

    def test_last_cue_end_never_exceeds_computed_total_duration(self):
        """Per-chunk local cues never leak past the chunk's own duration, so
        the absolute end of the last cue must fit inside the total concat
        timeline. If this invariant breaks we'd see captions outliving the
        audio — an easy foot-gun if any offset math drifted."""
        per_chunk_cues = {
            "c1": [(0.0, 1.0, "a")],           # chunk1 full duration
            "c2": [(0.0, 1.5, "b")],           # chunk2 full duration
            "c3": [(0.0, 2.0, "c")],           # chunk3 full duration
        }
        srt_strings = [_srt_from_cues(per_chunk_cues[t.chunk_id]) for t in self.TIMINGS]
        offsets = compute_chunk_offsets(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        merged = merge_srt_files(srt_strings, offsets)
        cues = parse_srt(merged)

        total = compute_total_duration(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        assert cues[-1].end_s == pytest.approx(total)
        assert cues[-1].end_s <= total + 1e-9

    def test_chunk_with_empty_cue_list_does_not_shift_neighbours(self):
        """If a chunk has no cues (e.g. a break-only chunk with no spoken
        words), the neighbouring chunks' offsets must still be computed from
        that chunk's *duration*, not skipped entirely."""
        per_chunk_cues = {
            "c1": [(0.0, 1.0, "spoken one")],
            "c2": [],  # silent, but still 1.5s of audio
            "c3": [(0.0, 2.0, "spoken three")],
        }
        srt_strings = [_srt_from_cues(per_chunk_cues[t.chunk_id]) if per_chunk_cues[t.chunk_id] else "" for t in self.TIMINGS]
        offsets = compute_chunk_offsets(
            self.TIMINGS, self.PADDING_S, self.SHOT_GAP_S
        )
        merged = merge_srt_files(srt_strings, offsets)
        cues = parse_srt(merged)

        assert len(cues) == 2
        # chunk1 cue unaffected.
        assert cues[0].text == "spoken one"
        assert cues[0].start_s == pytest.approx(0.0)
        assert cues[0].end_s == pytest.approx(1.0)
        # chunk3 cue starts at offset 3.2 even though chunk2 contributed no
        # cues — chunk2's 1.5s of audio + both gaps must still accumulate.
        assert cues[1].text == "spoken three"
        assert cues[1].start_s == pytest.approx(3.2)
        assert cues[1].end_s == pytest.approx(5.2)


# ---------------------------------------------------------------------------
# Regression fence for the sub-second rounding surface of format_srt_timestamp.
# ---------------------------------------------------------------------------


def test_offset_induced_fractional_ms_is_rounded_to_millisecond_grid():
    """Offsets that don't land on integer milliseconds must land on the ms
    grid in the final SRT — we don't pin banker's-rounding vs half-up (that
    is an implementation detail of ``format_srt_timestamp``), we only
    require that (a) the shift was actually applied, and (b) the end
    timestamp is still separated from the start by ~the original duration.

    This catches the class of bug where an integer-truncating offset
    implementation would floor 0.6ms to 0 and produce output identical to
    the unshifted case."""
    srt = _srt_from_cues([(0.0, 1.0, "x")])  # duration 1.0s
    merged_unshifted = merge_srt_files([srt], [0.0])
    merged_shifted = merge_srt_files([srt], [0.0012])  # 1.2ms shift

    # The 1.2ms shift must actually appear in the rendered SRT — a truncating
    # implementation would silently produce identical output.
    assert merged_shifted != merged_unshifted

    # Duration (end - start) is preserved to within 1ms regardless of rounding.
    shifted_cue = parse_srt(merged_shifted)[0]
    assert (shifted_cue.end_s - shifted_cue.start_s) == pytest.approx(
        1.0, abs=1e-3
    )
